name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: '--tests --all -- -D warnings'

      - name: clean
        uses: actions-rs/cargo@v1
        with:
          command: clean

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.12.4'
          args: '-- --test-threads 1'
          out-type: 'Html'

      - name: Upload code coverage results
        uses: actions/upload-artifact@v1
        if: ${{ always() }}
        with:
          name: code-coverage-report
          path: tarpaulin-report.html
